### ISSUE TITLE
investigate integrating CMake/Meson as build tool

### ISSUE THREAD

**Issue by ta5een** [ta5een/wyoos#2]
It seems that CMake is an industry-standard when architecting and compiling large C/C++ projects. The [Serenity OS project](https://github.com/SerenityOS/serenity) is a good example of one.

At the moment, I'm using a combination of `make` and `bear` to orchestrate the build process and notify the `clangd` LSP provider of changes to source files and compilation flags. However, I cannot find a way to use `bear` with the cross-compiler toolchain I've built (see #1) without specifying an absolute path. This is not ideal as the binaries for the toolchain are located relative to the project (in the `toolchains` directory), meaning it will be located in different places across different machines.

Since the Serenity OS project uses CMake _AND_ is able to use it with its own toolchain, I feel it would also be best for me to migrate to CMake. This would deprecate the `Makefile`s and `bear`-specific commands currently in use.

**Comment by ta5een** [comment]
Another build tool alternative is Meson. While not as popular as CMake, it does seem to be used in many OS projects I've looked into, such as [HelenOS](https://github.com/HelenOS/helenos).

Some things I like about Meson:

- [It has full support for cross compilation](https://mesonbuild.com/Cross-compilation.html)
- [It comes with a unit test system](https://mesonbuild.com/Unit-tests.html)

**Comment by ta5een** [comment]
# Tasks

- [x] Add `meson.build` scripts
- [x] Remove legacy build steps from Makefile
- [ ] Inform `clangd` to use `i686-elf-gcc` headers for LSP features (currently it thinks we want the headers from Clang 18)
- [ ] Investigate installing cross-tools in `$XDG_DATA_HOME/t5os/cross` (inspired by HelenOS)
- [ ] Update docs with new build instructions
